language: c++
os:
  - linux
  - osx
compiler:
  - gcc
  - clang

install:
  - CMAKE_VERSION=3.7.2
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v${CMAKE_VERSION%.[0-9]}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew install cmake || brew upgrade cmake
    fi
  - cmake --version

before_script:
  - cmake CMakeLists.txt
  - make common_utils_test -j2
  - make kktest_string_test -j2
  - make core_matchers_test -j2

script:
  - ./build/tests/common_utils_test
  - ./build/tests/common_utils_test -b
  - ./build/tests/kktest_string_test
  - ./build/tests/kktest_string_test -b
  - ./build/tests/core_matchers_test
  - ./build/tests/core_matchers_test -b
