language: c++
os:
  - linux
  - osx
compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - g++-7
    sources:
      - ubuntu-toolchain-r-test

before_script:
  - cmake CMakeLists.txt
  - make common_interproc_test -j2
  - make common_utils_test -j2
  - make common_string_test -j2
  - make kktest_extension_core_matchers_test -j2

script:
  - ./build/tests/common_interproc_test
  - ./build/tests/common_interproc_test -b
  - ./build/tests/common_string_test
  - ./build/tests/common_string_test -b
  - ./build/tests/common_utils_test
  - ./build/tests/common_utils_test -b
  - ./build/tests/kktest_extension_core_matchers_test
  - ./build/tests/kktest_extension_core_matchers_test -b
