language: cpp
os: linux

matrix:
  include:
    # GCC
    - env: COMPILER=g++-5
      addons:
        apt:
          packages:
            - g++-5
          sources:
            - ubuntu-toolchain-r-test

    - env: COMPILER=g++-6
      addons:
        apt:
          packages:
            - g++-6
          sources:
            - ubuntu-toolchain-r-test

    - env: COMPILER=g++-7
      addons:
        apt:
          packages:
            - g++-7
          sources:
            - ubuntu-toolchain-r-test

    - env: COMPILER=g++-8
      addons:
        apt:
          packages:
            - g++-8
          sources:
            - ubuntu-toolchain-r-test

    # CLang
    - env: COMPILER=clang++-3.6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6

    - env: COMPILER=clang++-3.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9
          packages:
            - clang-3.9

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]];
    then
      DEPS_DIR="${TRAVIS_BUILD_DIR}/deps";
      mkdir ${DEPS_DIR} && cd ${DEPS_DIR};
      travis_retry wget --no-check-certificate https://cmake.org/files/v3.12/cmake-3.12.4-Linux-x86_64.tar.gz;
      tar -xvf cmake-3.12.4-Linux-x86_64.tar.gz > /dev/null;
      mv cmake-3.12.4-Linux-x86_64 cmake-install;
      PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH;
      cd ${TRAVIS_BUILD_DIR};
      cmake --version;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];
    then
      brew install cmake;
      cmake --version;
    fi

script:
  - export CXX=${COMPILER}
  - export BUILD_TYPE=Release
  - ./test.sh
