language: cpp

matrix:
  include:
    # CLang on OSX
    - os: osx
      osx_image: xcode7.3
      env: COMPILER=clang++

    - os: osx
      osx_image: xcode8
      env: COMPILER=clang++

    - os: osx
      osx_image: xcode9.4
      env: COMPILER=clang++

    - os: osx
      osx_image: xcode10.1
      env: COMPILER=clang++

    # GCC on Linux
    - os: linux
      env: COMPILER=g++-5
      addons:
        apt:
          packages:
            - g++-5
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: COMPILER=g++-6
      addons:
        apt:
          packages:
            - g++-6
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: COMPILER=g++-7
      addons:
        apt:
          packages:
            - g++-7
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: COMPILER=g++-8
      addons:
        apt:
          packages:
            - g++-8
          sources:
            - ubuntu-toolchain-r-test

    # CLang on Linux
    - os: linux
      env: COMPILER=clang++-3.6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6

    - os: linux
      env: COMPILER=clang++-3.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9
          packages:
            - clang-3.9

    - os: linux
      env: COMPILER=clang++-4.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-4.0
          packages:
            - clang-4.0

    - os: linux
      env: COMPILER=clang++-5.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-5.0
          packages:
            - clang-5.0

before_install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - travis_retry wget --no-check-certificate https://cmake.org/files/v3.12/cmake-3.12.4-Linux-x86_64.tar.gz
  - tar -xvf cmake-3.12.4-Linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.12.4-Linux-x86_64 cmake-install
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  - cd ${TRAVIS_BUILD_DIR}
  - cmake --version

script:
  - export CXX=${COMPILER}
  - export BUILD_TYPE=Release
  - ./test.sh
