language: c++
os:
  - linux
  - osx
compiler:
  - gcc
  - clang

before_script:
  - cmake CMakeLists.txt
  - make

script:
  - ./build/tests/common_utils_test
  - ./build/tests/common_utils_test -b
  - ./build/tests/kktest_string_test
  - ./build/tests/kktest_string_test -b
  - ./build/tests/core_matchers_test
  - ./build/tests/core_matchers_test -b
